### PR TITLE
upgraded to pandas 2.1

### PR DESCRIPTION
**Pull request by tomsail**
`make test_full 
`
succeeded (excepted mayavi)

### CODE REVIEW

**Comment by tomsail** [comment]
Ok I might have problems to reproduce the fail here: I am trying to build as in the [CI](https://github.com/ec-jrc/pyPoseidon/blob/d32f16bee6968426f143f060f62d4ee37d9f0fca/.github/workflows/conda_pip.yml#L153): 

```
mamba create  --name pyposeidon --file locks/conda-ubuntu-latest-binary-p3.9.lock 
mamba activate schism
mamba activate --stack pyposeidon
python -mpip install -r "${REQUIREMENTS_CI}"
python -mpip install ./
```
last line actially updates pandas : 
```
Successfully built pyposeidon
Installing collected packages: tzdata, pandas, pyposeidon
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.3
    Uninstalling pandas-1.5.3:
      Successfully uninstalled pandas-1.5.3
Successfully installed pandas-2.1.2 pyposeidon-0.6.0 tzdata-2023.3
```

`make test_schism` passes for all 3 versions of python.

**Comment by tomsail** [comment]
sorry for the confusion. It was hard to debug and isolate the error. I have kept the changes minimal. PR ready to merge when GitHub CI will be finished.

**Comment by pmav99** [comment]
1. Please rebase and fixup the commits into a single one with an appropriate commit message (e.g. "Add pandas 2 compatibility"  or something similar)
2. if not too much trouble please test if this works with 1.X, too. I think It should. Just test it locally and if it is ok, then just remove the constraint from pandas - i.e. use `pandas = "*"`

Other than that, good work!

**Comment by tomsail** [comment]
Thanks @pmav99. Yes tried already the option on my laptop. It should work

**Pull request merged**
